jobs:
  show_me:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: |
        echo "Repository: ${{ github.repository }}"
        echo "Branch: ${{ github.ref_name }}"
        echo "Commit SHA: ${{ github.sha }} "